#!/bin/zsh

source variables.sh

set -e
set -x

ssh-keyscan -t rsa >> ~/.ssh/known_hosts

source stages/upload_self.zsh
# stages/bootstrap_root_user.zsh
ssh root@${BOXROOT_IP} '/bin/bash /tmp/bootstrap/stages/bootstrap_root_user.zsh'
