#!/bin/zsh

source variables.sh

set -e
set -x

ssh-keyscan -t rsa ${BOXROOT_FQDN} >> ~/.ssh/known_hosts

source stages/upload_self.zsh
ssh root@${BOXROOT_FQDN} '/bin/bash /tmp/bootstrap/stages/bootstrap_root_user.zsh'
ssh root@${BOXROOT_FQDN} 'rm -rf /tmp/bootstrap*'
