source application.sh
source sensitive.sh

BOXROOT_LOGICAL_NAME=root

BOXROOT_ROOT_NAME=root
BOXROOT_ROOT_USERNAME=${BOXROOT_ROOT_NAME}+${BOXROOT_LOGICAL_NAME}
BOXROOT_ROOT_EMAIL=${BOXROOT_ROOT_USERNAME}@${APPDOMAIN}
